version: "3.1"
services:
  run_lake_metrics:
    image: jrossusgs/lake-temperature-out:v0.2
    build:
      context: .
    ports:
      - "8787:8787"
    volumes:
      - type: bind
        source: ../
        target: /lakes
    environment:
      - ROOT=TRUE
      - PASSWORD=mypass
